# -*- mode: python ; coding: utf-8 -*-
"""
小说创作应用 PyInstaller 打包配置
"""

a = Analysis(
    ['../novel_app.py'],
    pathex=['..'],
    binaries=[],
    datas=[
        ('../novel_data', 'novel_data'),
    ],
    hiddenimports=[
        'app',
        'app.config',
        'app.ai_client',
        'app.image_generator',
        'app.scene_detector',
        'app.memory_manager',
        'app.note_manager',
        'app.fullscreen_writer',
        'app.novel_agent',
        'app.reading_manager',
        'app.ui_style',
        'app.writing_skills',
        'app.writing_skills_panel',
        # P2-1 巨石拆分产生的功能域 Mixin
        'app.shell_ui',
        'app.lifecycle_ui',
        'app.generation_ui',
        'app.character_ui',
        'app.outline_ui',
        'app.chapter_ui',
        'app.editor_ui',
        'app.reader_ui',
        'app.timeline_ui',
        'app.toolkit_ui',
        'app.persistence_ui',
        'app.note_ui',
        'app.parsing',
        'app.panels',
        'app.panels.elements_panel',
        'app.panels.bridges_panel',
        'app.panels.descriptions_panel',
        'app.panels.dialogue_panel',
        'app.panels.story_flow_panel',
        'app.panels.style_panel',
        'app.panels.adapt_panel',
        'app.panels.websearch_panel',
        'app.panels.memory_viz_panel',
        'app.panels.summary_mgmt_panel',
        'app.panels.batch_ops_panel',
        'app.panels.chapter_analysis_panel',
        'app.storage',
        'app.novel_toolkit',
        'app.character_system',
        'app.format_converter',
        'app.cloud_storage',
        'tkinter',
        'tkinter.ttk',
        'tkinter.messagebox',
        'tkinter.filedialog',
        'tkinter.simpledialog',
        'tkinter.scrolledtext',
        'httpx',
        'json',
        'threading',
        'webbrowser',
        'loguru',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib',
        'scipy',
        'PIL',
        'numpy',
        'pandas',
        'chromadb',
        'sentence_transformers',
        'fastapi',
        'uvicorn',
        'pydantic',
    ],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='../AI_NovelWriter',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,  # 改为False隐藏控制台窗口
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='../icon.ico',
)
